services:
  - type: web
    name: shortform-content-planner-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BUBBLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16